# Generated by Django 5.2.15 on 2026-10-08 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("db", "0123_wikicollection_page_collection"),
    ]

    operations = [
        migrations.AddField(
            model_name="workspace",
            name="disabled_app_sections",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
